name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - gcc_linux-64
  - curl
  - zlib
  - numpy
  - pytest
  - pyBigWig
  - pandas
  - pytorch
  - pytorch-lightning
  - wandb
  - pip
  - pip:
    - gReLU
